name: Close stale issues
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 1
          days-before-close: 1
          stale-issue-message: 'This issue is stale due to inactivity.'
          close-issue-message: 'Closing this issue after prolonged inactivity.' 
          only-issues: true
